### ISSUE TITLE
Error while generating reports from VM servers

### ISSUE THREAD

**Issue by oscoder7** [dfaruque/Serenity.Extra#108]
Hi ,

When I am publishing contents to hosting providers such as myasp.net I am able to get the reports 
but when I place the same in a azure vm the reports are not working and it is giving the below error, 

Really appreciate any guidance 

An unhandled exception occurred while processing the
 request.
 ArgumentOutOfRangeException: Specified argument was out of the range of
 valid values. (Parameter 'reportKey')
 SerExtraCore.ReportContro ler.Execute(string key, string opt, string ext, bool download, bool printing) in
 ReportController.cs, line 40

**Comment by dfaruque** [comment]
Hello,
I have no Azure VM to reproduce the error. Sorry!
Please check the ReportKey as the error says.

**Comment by oscoder7** [comment]
It’s okay it got it resolved when I configured it as a separate site in IIS
with inprocess
