### ISSUE TITLE
Version Compatibility

### ISSUE THREAD

**Issue by wildanmuhlis2** [dfaruque/Serenity.Extra#11]
Hi, thanks for great extras.

Is the extra compatible with latest serenity? (3.7.1)

I've tried to install it but error message come up.
```

SCRIPT ERROR! See browser console (F12) for details.
Message: Uncaught TypeError: MonitoringKontrakSerene.Procurement.ProcRequestGrid is not a constructor

File: http://localhost:52230/Scripts/jquery-3.3.1.js?v=agfan66TS68_dJ6Ha7_dlg2, Line: 3827, Column: 3

SCRIPT ERROR! See browser console (F12) for details.
Message: Uncaught TypeError: Cannot read property 'prototype' of undefined

File: http://localhost:52230/Scripts/serenity/Serenity.CoreLib.js?v=XYq46sT4t4v4KfKcUuCcEA2, Line: 21, Column: 69
```

Could you help me to install it?

Thanks,

Wildan

**Comment by dfaruque** [comment]
As my knowledge it is compatible.

I seems to me that you typescript does not compiled successfully.

to ensure that you could delete the ~Scripts/site/xxx.web.js file
then build the solution and see output window to check is there any warning related to typescript?

**Comment by wildanmuhlis2** [comment]
Hi, thanks for your guide, when trying rebuild the solution after deleting xxx.web.js, this warning message occured

```
1>------ Build started: Project: YYYSerene.Web, Configuration: Debug Any CPU ------
1>  YYYSerene.Web -> C:\Users\xxx\source\repos\YYYSerene\YYYSerene\YYYSerene.Web\bin\YYYSerene.Web.dll
1>  Executing TypeScript compiler...
1>C:\Users\xxx\source\repos\YYYSerene\YYYSerene\YYYSerene.Web\Modules/Procurement/ZZZ/ZZZDialog.ts(6,49): warning TS2449: Class 'DialogBase' used before its declaration.
1>  
1>C:\Users\xxx\source\repos\YYYSerene\YYYSerene\YYYSerene.Web\Modules/Procurement/ZZZ/ZZZGrid.ts(6,47): warning TS2449: Class 'GridBase' used before its declaration.
1>  
1>C:\Users\xxx\source\repos\YYYSerene\YYYSerene\YYYSerene.Web\YYYSerene.Web.csproj(3137,5): warning MSB3073: The command ""C:\Users\xxx\source\repos\YYYSerene\packages\Microsoft.TypeScript.MSBuild.2.8.3\tools\tsc\tsc" -p ./tsconfig.json" exited with code 2.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

```
It's could be resolved with adding reference in `xxxDialog.ts` and `xxxGrid.ts`

`/// <reference path="../../_Ext/Bases/DialogBase.ts" />`

Is it the best way to do it? if yes it's better to mention this reference in `Readme / wiki`

Thanks,

Wildan

**Comment by wildanmuhlis2** [comment]
I need to reference the `/// <reference path="../../_Ext/Bases/DialogBase.ts" />` because i've used later version of type script `(2.8.3)` when rebuild with recommended version of typescript `(2.5.2)`, it's work like a charm :)
