### ISSUE TITLE
How to Use Sergen *.scriban template

### ISSUE THREAD

**Issue by wildanmuhlis2** [dfaruque/Serenity.Extra#12]
Hi dfaruque,

I've trying to point sergen template to sergen extra template,

`_Ext\CodeGeneratorTemplates`

![image](https://user-images.githubusercontent.com/11847279/41752510-10c90aba-75f2-11e8-91f1-b9a190905619.png)

Code generator completed successfully but it's not inherit base class from serenity extra, the generated code same as default.

How to use the template?

Thanks,

Wildan

**Comment by dfaruque** [comment]
you need to restart sergen to affect the changes in sergen options.

**Comment by wildanmuhlis2** [comment]
@dfaruque Thanks, it works !!! :)
