### ISSUE TITLE
Remove Button

### ISSUE THREAD

**Issue by rezafd23** [dfaruque/Serenity.Extra#13]
Hi @dfaruque, i've used your extra, i want to ask, is there possible to remove "New Notification" and export button?
![image](https://user-images.githubusercontent.com/31206753/42263579-a85dbb00-7f98-11e8-8b37-eb49cd4195e9.png)

thanks

**Comment by wildanmuhlis2** [comment]
@rezafd23 Have a look https://github.com/volkanceylan/Serenity/wiki/Cheat-Sheet#add-or-remove-a-button
