### ISSUE TITLE
CardViewMixin switch back to List (which was the default view) when paging

### ISSUE THREAD

**Issue by YYOHAN** [dfaruque/Serenity.Extra#17]

**Comment by dfaruque** [comment]
Don't understand. Please explain more.

**Comment by YYOHAN** [comment]
You have a grid using CardViewMixin and the view type is set by default to List, when you click to switch to card view and then try to go to the next page (clicking on the pagination button), the list view shows on top and at the bottom of the page the card view shows (both the list and the card view shows at the same time).
by the way, very good enhancements to the Serenity framework.

**Comment by YYOHAN** [comment]
It is something on my side, in your solution works fine.
Thank you

**Comment by Zahar661** [comment]
@YYOHAN hi! Can you share an example itemTemplate?
