### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by minhhungit** [dfaruque/Serenity.Extra#18]
hello @dfaruque 
This is just a suggestion!

I think it is really good if we have a demo page to show your features and how to implement them for newbie developer, like serenity demo page

What do you think, thank you for sharing your **Extra** features

**Comment by dfaruque** [comment]
Thank you for your suggestion.
Yes, it will be good to have the demo page.

Later I will consider it.

**Comment by vinaykulkarni89** [comment]
This would really help

**Comment by edwardch** [comment]
Cool! Is it best if I contact you directly via email to work out our requirements?

**Comment by dfaruque** [comment]
Yes, please.

**Comment by edwardch** [comment]
Message sent, please check your spam in case it doesn't come through to your inbox.

**Comment by minhhungit** [comment]
any news guys

**Comment by edwardch** [comment]
Sorry, almost there. I've been super busy with work but hopefully in the next day or two I can give you guys a demo...

**Comment by edwardch** [comment]
Here we go, guys: [https://serenity-extra.azurewebsites.net](https://serenity-extra.azurewebsites.net)

Question: Do you think I should periodically drop all the tables in the database so that the migrations run and recreate everything with fresh data?

**Comment by minhhungit** [comment]
Nice @edwardch & @dfaruque, thank you !

>Do you think I should periodically drop all the tables in the database so that the migrations run and recreate everything with fresh data

I think we should

**Comment by minhhungit** [comment]
it looks there are some features did not work, where is source code for demo page, if I want to create pull request to update something in future, can I do that

**Comment by dfaruque** [comment]
@edwardch thank you for your support.

one question: does it automatically publish when there are new commits?

**Comment by edwardch** [comment]
> one question: does it automatically publish when there are new commits?

I have set this up for my personal projects, but not yet for Serenity.Extra. I will try to do this though.

For now you're welcome to ping me and I'll pull/build/publish.

**Comment by Zahar661** [comment]
Main Grid Multi-Editing not working

**Comment by edwardch** [comment]
@dfaruque I think we should close this issue because there is a demo running. 

@Zahar661 did you check the exceptions log under Administration/Exceptions Log ?

Other issues should probably be opened as new issues, specifying the steps required to reproduce the errors. Unfortunately I am not the maintainer of this repo, I'm just helping out by hosting this demo.

**Comment by dfaruque** [comment]
@Zahar661 
Main Grid Multi-Editing is not completed yet.

**Comment by edwardch** [comment]
@dfaruque just a ping to say I've deployed up to your latest commit. 

I do check every few days, unfortunately I don't have much time to set up CI...

Thanks for all the work!

**Comment by dfaruque** [comment]
@edwardch Thank you very much for your time and support.
