### ISSUE TITLE
Audit insert disabled

### ISSUE THREAD

**Issue by Zahar661** [dfaruque/Serenity.Extra#19]
Hi! 
Work super, thanks! 
Why was insert disabled? 
Error in handler.Old or is there information in the first version of the update?

![image](https://user-images.githubusercontent.com/26430136/49136347-cc6d4f00-f302-11e8-9a7d-b549b2210a8f.png)

**Comment by dfaruque** [comment]
I have intentionally disabled it. Because of InsertData and InsertUser should be in the table field. there is no data change to log actually while inserting.
Another issue is bulk inserting the large dataset will be very slow while insert audit log is enabled.

By the way, you may enable it if you need.

**Comment by asilmertkan** [comment]
Hi!
Thanks for good job! 
Sorry for write on closed issue, so my issue about this.
I used ex version and I update it, So now I didn't see Create and Delete log. How I can enable it?
Is there a way you can suggest? 
Thanks Again...

**Comment by dfaruque** [comment]
implement `IAuditLog` in which Row/Entity you want to log. like the following
`public sealed class OrderRow : Row, IIdRow, INameRow, _Ext.IAuditLog`

**Comment by asilmertkan** [comment]
Hi again,

I already implement it and It worked perfect in ex-version. But last version seem just "update" logs. I looked for your azure sample website and I saw same issue in there too. I added a new customer as "abc" then looked logview and I did'nt see a log for this record.

**Comment by dfaruque** [comment]
Please uncomment the highlighted code (shown in the screenshot above) for now.
