### ISSUE TITLE
Grid Inline Editable

### ISSUE THREAD

**Issue by MaradiagaSistemas** [dfaruque/Serenity.Extra#2]
Hi @dfaruque,

Thanks for this amazing Extra Help on Serenity, amazing job,

I was wondering if is posible to setup a Grid Inline Editable with cascading Dropdowns? 

Sending a Picture, Thanks in advance.

![imagen](https://user-images.githubusercontent.com/1533653/32499027-fa077590-c396-11e7-83e5-66ff675bf3ba.jpg)

**Comment by dfaruque** [comment]
I have not implement cascading lookup. may be later I will try...
I will be happy if someone like you implement this :smile:

**Comment by MaradiagaSistemas** [comment]
Perfect, I will be glad to help.

Thanks!

**Comment by dfaruque** [comment]
cascading lookup is now supported
