### ISSUE TITLE
in order pick product select one product and then use pager and than select second product of second page. ok button is not work . How can i use it?

### ISSUE THREAD

**Issue by jaamkamran** [dfaruque/Serenity.Extra#26]
![20190326_173859](https://user-images.githubusercontent.com/36103038/54997865-898c6100-4fee-11e9-9925-d56be3a1920e.gif)

**Comment by dfaruque** [comment]
Hmm. there is an issue.

I have to look in free time.

**Comment by jaamkamran** [comment]
sir, your work is help for us. we implement this feature in client project.
when we click one row and then in next page we select another row and press
ok button it show me error that your product id is not define.. hope will
get the best response from you. thanks

**Comment by jaamkamran** [comment]
![image](https://user-images.githubusercontent.com/36103038/55161499-7cef4080-5187-11e9-9e5c-0f4f8f21dc74.png)

**Comment by jaamkamran** [comment]
Thanks Dear.Allah bless you.
Ameen
