### ISSUE TITLE
Inline edit grid - Cascaded field work?

### ISSUE THREAD

**Issue by mustafalotiya** [dfaruque/Serenity.Extra#28]
Hi,

Does inline editor support cascaded field. Parent Id field is also available on same grid.

 I have Project Id and Project Task Id field on grid. Project Task Id is cascaded field from Project Id.  

Thanks in advance. 

Please provide sample code if same is supported in inline grid.

**Comment by dfaruque** [comment]
Sorry, the cascade is not supported in inline grid yet.

**Comment by mustafalotiya** [comment]
Thanks for confirmation.

**Comment by mustafalotiya** [comment]
Is there any way, we can load different drop down values for different rows depending  manually. 
![image](https://user-images.githubusercontent.com/23294782/57190966-7b0c6000-6f31-11e9-9b4d-96270249d13b.png)

In above example,
Group1, Group2, Group3  and Product fields are drop down editor.
As cascade is not supported in editable grid, can load manually drop down ?

**Comment by dfaruque** [comment]
it should work.
