### ISSUE TITLE
Inline editing for Enum

### ISSUE THREAD

**Issue by vinaykulkarni89** [dfaruque/Serenity.Extra#29]
Hi @dfaruque, how can we have formatter for inline editing of grid for Enum type editors

**Comment by vinaykulkarni89** [comment]
@dfaruque 
Can you guide for the same

**Comment by dfaruque** [comment]
Sorry, for now, I have no such example.

**Comment by vinaykulkarni89** [comment]
Ok

**Comment by dfaruque** [comment]
closing due to aging!
