### ISSUE TITLE
Demo Shutdown

### ISSUE THREAD

**Issue by edwardch** [dfaruque/Serenity.Extra#33]
Hi @dfaruque, 

Unfortunately I have run out of free credits on Azure and will no longer be able to host the demo app for you, so I'm about to shut it down :(

Sorry guys! 

Cheers,
Edward

PS. For cheap hosting options, you could deploy it to Azure on a free App Service tier (60 mins of compute/day), and a Basic tier 5 DTU database for ~$5/month. 
Another option would be to convert to .NET Core then host it on something like DigitalOcean for $5/month.

**Comment by choss21** [comment]
Hi good day
because they do not upload it in https://somee.com/default.aspx,
it's free, only a small advertisement appears

**Comment by jmkamran** [comment]
https://www.youtube.com/channel/UC6drRBHd5J7pcGYGPBK0M7Q
subscribe my channel for more help of serenity
