### ISSUE TITLE
Installition and Jquery Not Defined Error

### ISSUE THREAD

**Issue by muhammedyaman** [dfaruque/Serenity.Extra#37]
This is a great extra for serenity thank you for this. I have a question about installition. I am installing to an existing start# project.  3rd step says "Change Base/Super classes of Dialog.ts and Grid.ts using following mappings" which files should i modify? my xyzdialogs and xyzgrids one by one?

Also I am having an issue after i complete the steps except the 3rd one.
![image](https://user-images.githubusercontent.com/44383772/79861055-6c39ea00-83dc-11ea-86de-c34932b43c1a.png)

**Comment by dfaruque** [comment]
For JQuery related error: you should include the files after jquery. i.e after the following line in LayoutHead.cshtml file.
 `@Html.ScriptBundle("Base")`

For the 3rd step: yes. you are correct. if you want to use Serenity.Extra grid/dialog base to all of your grids/dialogs then you could you find-replace. 
for dialog,
Search term: ` extends Serenity.EntityDialog<`
Replace term: ` extends _Ext.DialogBase<`

for grid,
Search term: ` extends Serenity.EntityGrid<`
Replace term: ` extends _Ext.GridBase<`

**Comment by muhammedyaman** [comment]
Thank you. This is a great extra!
