### ISSUE TITLE
SerExtra is not defined

### ISSUE THREAD

**Issue by Nathan2020-0126** [dfaruque/Serenity.Extra#42]
I have justed download the project code and running in my computer. I can build it successfully but I cannot see the page content, below is the error information.
```
SerExtra is not defined
```
![image](https://user-images.githubusercontent.com/16734387/84503821-78ac3600-aced-11ea-89a8-fd0cd0efc709.png)

**Comment by Nathan2020-0126** [comment]
I don't konw why, the problem is auto solved.

**Comment by dfaruque** [comment]
Maybe it fails in the first build. After second build it is fixed.
