### ISSUE TITLE
EnumHelper.cs -> Duplicate File

### ISSUE THREAD

**Issue by ArsenioInojosa** [dfaruque/Serenity.Extra#48]
Hello, following the instructions for use produces an error: the EnumHelper.cs file is duplicated.

How to use (for .net core)
Copy the Modules/_Ext folder from the SerExtraCore project and place it accordingly.

"SerExtraCore.Web\Modules\_Ext\Utils\EnumHelper.cs"
"Modules\Common\Helpers\EmailHelper.cs"

My solution was to delete the first one.

Thank you!

**Comment by dfaruque** [comment]
OK
