### ISSUE TITLE
How is the MonthYearEditor used?

### ISSUE THREAD

**Issue by ArsenioInojosa** [dfaruque/Serenity.Extra#49]
Hi all,

Does anyone know if the MonthYearEditor can be used as a filter on a grid?

This doesn't work for me:
```
[QuickFilter, MonthYearEditor]
public DateTime InsertDate {get; set; }
```

Thank you very much!

**Comment by muhammedyaman** [comment]
I don't know if you solved this but `[QuickFilter, MonthYearEditor]` put this in xyzRow and that should work.

**Comment by ArsenioInojosa** [comment]
Hi, I already solved it by creating my own editor. I just wanted to know why it doesn't work on the column like the other Serenity editors.

Thanks
