### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by vinaykulkarni89** [dfaruque/Serenity.Extra#5]
Hi @dfaruque, these features seem excellent, installing package Serenity.Extra.

**Comment by dfaruque** [comment]
Happy to hear that.

**Comment by brunobola** [comment]
@dfaruque Trully excellent work, keep adding new features ;)

**Comment by vinaykulkarni89** [comment]
@dfaruque 
Can we have a changelog for this repository similar to our Serenity, so that it will help to understand new features

**Comment by dfaruque** [comment]
@vinaykulkarni89 nice idea
I will maintain changelog from now.

**Comment by vinaykulkarni89** [comment]
@dfaruque 
Once again thanks q.SetEditorLabel was too useful in some case
