### ISSUE TITLE
AutoColumnResize - Examples and Collaboration

### ISSUE THREAD

**Issue by ArsenioInojosa** [dfaruque/Serenity.Extra#50]
Hello @dfaruque , first of all I would like to congratulate you on your work. It has very interesting options that are not included in the Serenity Framework.

I have known this project for a couple of years and at the time I adapted the AuditLog for my projects.

Now that the project works in Net Core, I want to fully integrate them into my projects. I am conducting integration tests and verifying the overall operation of the system.

The main problem is that there are no examples for most of the functions, I want to collaborate with this and also add new features. Today I detected a small error in the names of the properties (see image).

![image](https://user-images.githubusercontent.com/11929923/88492089-480b1d80-cf76-11ea-9ad1-30c5859a69f3.png)

Column resizing doesn't work properly either. It is adjusted by the headers but does not take into account the content of the cell. As I see it, it is more important to see the content than the header, especially if it is a number, code or currency. The plugin https://github.com/volkanceylan/Serenity/wiki/Grid:-Slickgrid-AutoColumn-resize works fine, however you made modifications. Any specific reason for that change?

Please see the following GIF to better understand what I mean:

![Resize](https://user-images.githubusercontent.com/11929923/88492011-776d5a80-cf75-11ea-960d-9cef982e1917.gif)

Sincerely, Arsenio.

**Comment by dfaruque** [comment]
Thank you @ArsenioInojosa 
You are right. Content is more important than the header.
There is nothing special reason except for my lack of knowledge at that moment. Hopefully, I will fix that.
