### ISSUE TITLE
GridItemPicker InplaceSearch open dialog on enter key event

### ISSUE THREAD

**Issue by reach2rv** [dfaruque/Serenity.Extra#52]
Hi @dfaruque 

I am able to make inplace search on GridItemPicker Editor keyboard focusable by adding attribute tabindex= 0. how I can achieve onclick using the enter key? this can make the button keyboard accessible for the end-user making system keyboard friendly

**Comment by reach2rv** [comment]
Resolved.. 

Will post code soon. 

@dfaruque I am facing warning no single or multiple option is selected. Whereas I am assigning Multiple= false in Row for GridItemeditor attribute. What am I doing wrong?

**Comment by dfaruque** [comment]
in the grid constructor, put a second parameter
```
        constructor(container: JQuery, options) {
            super(container, options);

        }
```

**Comment by reach2rv** [comment]
@dfaruque last one how to make textbox of GridItemeditor editable ?

**Comment by dfaruque** [comment]
currently, text box is not editable. need to develop this feature

**Comment by reach2rv** [comment]
It is a good feature to have as user can enter value known to him Instead of opening select dialog and rest can be handled in changeselect2 for the text box
