### ISSUE TITLE
AutoFit Content Area add blank white space to the form

### ISSUE THREAD

**Issue by reach2rv** [dfaruque/Serenity.Extra#58]
Hi,

When I use _Ext.DialogBase with ExtDialog default option set to AuthofitContentArea = true; it adds white space after in the end which extends the height of form.

Can you please suggest how to get rid of it?

**Comment by dfaruque** [comment]
in ScriptInitialization.ts file add the following line
`    q.DefaultEntityDialogOptions.AutoFitContentArea = false;`
