### ISSUE TITLE
There is no BasedOnRowAttribute in the form with FormKey Error

### ISSUE THREAD

**Issue by muhammedyaman** [dfaruque/Serenity.Extra#61]
Hi. I am trying to use AuditLog Viewer in dialog. AuditLog is kept nicely and I can see the data in AuditLog page. But in dialog button for auditlog history is giving me this error: 
![image](https://user-images.githubusercontent.com/44383772/107208873-33bed780-6a13-11eb-913b-9451379fe1a1.png)

There is infact a basedonrowattribute in my TekliflerForm which has the "Musteri.Teklifler" formkey.
`    [FormScript("Musteri.Teklifler")]
    [BasedOnRow(typeof(TekliflerRow), CheckNames = true)]
    public class TekliflerForm
    {
`
Any suggestions?

**Comment by dfaruque** [comment]
When I have designed, it was working. but many updates in serenity is made periodically. Need to sync it with the latest.

**Comment by muhammedyaman** [comment]
Thank you for your response. I will post here if I find a solution.

**Comment by muhammedyaman** [comment]
I don't know why but I changed the FormKey of my form from "Musteri.Teklifler" to "Musteri.Tekliflerrr" and it did the trick. I really wonder why but i think i wont be able to figure out. Closing.
