### ISSUE TITLE
Tutorial For Serenity 5

### ISSUE THREAD

**Issue by muhammedyaman** [dfaruque/Serenity.Extra#64]
hello @dfaruque is there going to be a tutorial for serenity 5?

**Comment by dfaruque** [comment]
Yes. But don't know when. Because, I am busy for my office work nowadays.

**Comment by muhammedyaman** [comment]
Looking forward to it. Good luck with your office work.

**Comment by muhammedyaman** [comment]
You are the best! Thanks.
