### ISSUE TITLE
how to  use report design path at client side

### ISSUE THREAD

**Issue by reach2rv** [dfaruque/Serenity.Extra#66]
Hi @dfaruque

I want to give flexibility to user to define report format for each voucher and then at runtime fetch the design view and load data in that to generate report. can you please brief me how I can use your _Ext Reporting to achieve the same.

**Comment by dfaruque** [comment]
You can create a report design file (.cshtml) with the simple two line
```
@model YourModel

@Html.Raw(Model.ReportContent)
```

Model.ReportContent should contain the HTML markup
