### ISSUE TITLE
IAuditLog issue on .Net Core 5 SQLite

### ISSUE THREAD

**Issue by vinaykulkarni89** [dfaruque/Serenity.Extra#73]
We are using .net Core 5 with SQLite, when IAuditLog is enabled update operation takes 30 sec, the same tested with SQLServer works fine

**Comment by dfaruque** [comment]
I have with Sqlite and it working without problem.
Please make sure you have the updated files from SerExtraNet5 project.

**Comment by vinaykulkarni89** [comment]
Hi @dfaruque  we have used the files from SerExtraNet5

**Comment by dfaruque** [comment]
run the SerExtraNet5 from your machine. I don't have problem at my end.
