### ISSUE TITLE
RunSergen not working properly

### ISSUE THREAD

**Issue by ArsenioInojosa** [dfaruque/Serenity.Extra#76]
Hi,

This happens in Net 5. Please check when you can

![image](https://user-images.githubusercontent.com/11929923/176803444-f463e8f2-505a-4722-9c9e-6b96a776e9ae.png)

**Comment by dfaruque** [comment]
hmm. may be there are breaking changes. please consider using sergen through CLI.

**Comment by dfaruque** [comment]
I have checked and this is working at my end.
