### ISSUE TITLE
Heroku free plan to be discontinued

### ISSUE THREAD

**Issue by edwardch** [dfaruque/Serenity.Extra#78]
Hey @dfaruque, 

I see you went through the efforts of setting up a demo on Heroku (which is great to see hosting work on such a platform, by the way!). 

Heroku (owned by Salesforce) have announced that they are discontinuing their free plan: https://blog.heroku.com/next-chapter

I've seen a few people suggest using Fly.io as a Heroku replacement, and I see that you can host small apps for free with it. Looks like they have something to help you migrate, too: https://fly.io/launch/heroku

There may be other options out there (including paying for a Heroku dyno, which probably won't want to do), but so far Fly.io seems to be a good alternative.

Wonder if you, or anyone else, have thoughts on this?

Cheers,
Edward

**Comment by edwardch** [comment]
HN discussion on alternatives: [Tell HN: Heroku alternatives with generous free tiers](https://news.ycombinator.com/item?id=32599398)

**Comment by dfaruque** [comment]
Thank you very much for the info. I will investigate Fly.io or others.
