### ISSUE TITLE
How do I create an autocomplete filter by name using the product completion code to direct invoice؟

### ISSUE THREAD

**Issue by ahmedabdelh** [dfaruque/Serenity.Extra#86]
let $barcodeInput = $('<input type="text" />');

            $barcodeInput.appendTo(this.toolbar.element)
                .keypress(event => {
                    if (event.keyCode == 13) {
                        let productId = $barcodeInput.val();

                        if (productId) {
                            let eqFilter = {};
                            eqFilter[ProductRow.Fields.ProductID] = productId

                            ProductService.List({ EqualityFilter: eqFilter, Take: 1 }, response => {
                                if (response.Entities.length > 0) {
                                    let pickedProduct = response.Entities[0];

                                    let orderDetails = this.value;
                                    orderDetails.push({
                                        ProductID: pickedProduct.ProductID,
                                        ProductName: pickedProduct.ProductName,
                                        UnitPrice: pickedProduct.UnitPrice,
                                        Quantity: 1,
                                        LineTotal: 1 * (pickedProduct.UnitPrice || 0)
                                    });

                                    this.value = orderDetails;
                                } else {
                                    Q.alert('Product not found!')
                                }
                            });
                        }
                    }
                });

**Comment by muhammedyaman** [comment]
Can you explain a little more?
