### ISSUE TITLE
Modification on the grid.ts does not work after adding this code

### ISSUE THREAD

**Issue by ahmedabdelh** [dfaruque/Serenity.Extra#87]
Modification on the grid.ts does not work after adding this code..
*******************************************************
  protected getSlickOptions() {
            let opt = super.getSlickOptions();
            opt.editable = true;
            return opt;
        }
****************************************************

**Comment by muhammedyaman** [comment]
This only works for Editor Grids. If you want to use this in Grid.ts you have to configure gridbase for that. Or if you are a startsharp user [this](https://demo.serenity.is/AdvancedSamples/InlineEditing) is the sample.
