### ISSUE TITLE
Asp.net core version support

### ISSUE THREAD

**Issue by adalberto-argente** [dfaruque/Serenity.Extra#9]
I tried installing the nuget package in a project using the asp.net core version of serenity and it did not work. The installation runs successfully, but the files are not created in the project.

Is there anything I can do to get around this or is it really not compatible?

And congratulations for the excellent work !!!

**Comment by dfaruque** [comment]
I did not try it with asp.net core version.
Maybe later, I will try to make a different NuGet package for core version.

**Comment by dfaruque** [comment]
BTW, you may clone it and copy the Modules/_Ext folder into your Modules folder.

**Comment by adalberto-argente** [comment]
All right, I'll try to do that. Thank you!

**Comment by amiradib** [comment]
I Copy Modules/_Ext folder but _Ext.Entities in AuditLogViewerController hasn't recognized
i think nuget package don't work in serenity core version,

do you have any solution?

**Comment by fwd079** [comment]
None of the suggestions worked sadly.
Gets my vote though, would be great.

**Comment by dfaruque** [comment]
https://github.com/dfaruque/Serenity.Extra#how-to-use-for-net-core

**Comment by Hochmah** [comment]
> https://github.com/dfaruque/Serenity.Extra#how-to-use-for-net-core

I tried that and it didn't work.
